---
title: "BRFSS 2016 to 2020"
output: html_document
---

Read data
```{r, message = FALSE}

# Read in output csv with 5 years' data (half a minute)
c5 <- read.csv('brfss_5y.csv', header=T, na.strings=c(""," ", "NA"))

# Just keep the columns I need for one analysis
c5 <- c5[, c("sex", "age.g", "race", "ststr", "psu", "finalwt")]
c5 <- c5[, c("year", "ment14d", "sex", "age.g", "race", "educag", "income2",
             "ststr", "psu", "finalwt")]

```

Recode for plotting, keeping Refused/Missing category
```{r}

library(dplyr)

# MH
c5$ment14d <- factor(c5$ment14d)
table(c5$ment14d, useNA='a')
c5$ment14d_rc <- recode(c5$ment14d, 
                        "1" = "0 days", 
                        "2" = "1-13 days", 
                        "3" = "14+ days", 
                        "9" = "Refused_Missing")
# Sex
c5$sex <- factor(c5$sex)
table(c5$sex, useNA='a')
c5$sex_rc <- recode(c5$sex, 
                    "1" = "Male", 
                    "2" = "Female",
                    "7" = "Refused_Missing", 
                    "9" = "Refused_Missing")
# Age
c5$age.g <- factor(c5$age.g)
table(c5$age.g, useNA='a')
c5$ageg_rc <- recode(c5$age.g, 
                    "1" = "18_24", 
                    "2" = "25_34",
                    "3" = "35_44", 
                    "4" = "45_54",
                    "5" = "55_64",
                    "6" = "65_older")
# Race
c5$race <- factor(c5$race)
table(c5$race, useNA='a')
c5$race_rc <- recode(c5$race, 
                    "1" = "white", 
                    "2" = "black",
                    "3" = "native", 
                    "4" = "asian",
                    "5" = "pacific",
                    "6" = "other",
                    "7" = "multi",
                    "8" = "hispanic",
                    "9" = "Refused_Missing")
# Education
c5$educag <- factor(c5$educag)
table(c5$educag, useNA='a')
c5$educag_rc <- recode(c5$educag, 
                    "1" = "less_high_school", 
                    "2" = "high_school",
                    "3" = "some_college", 
                    "4" = "college",
                    "9" = "Refused_Missing")
# Income
c5$income2 <- factor(c5$income2)
table(c5$income2, useNA='a')
c5$income2_rc <- recode(c5$income2, 
                    "1" = "10_less", 
                    "2" = "10_15",
                    "3" = "15_20", 
                    "4" = "20_25",
                    "5" = "25_35",
                    "6" = "35_50",
                    "7" = "50_75",
                    "8" = "75_more",
                    "77" = "Refused_Missing",
                    "99" = "Refused_Missing")
```

Recode for stats, binary with NA
```{r}

# Original is all integers

# NOTE: best to step through line by line, for large datasets? 
# gave a weird table when running chunk of code all together

# MH
c5$ment14d_n <- NA
c5$ment14d_n[c5$ment14d == 1] <- 0
c5$ment14d_n[c5$ment14d %in% c(2,3)] <- 1
table(c5$ment14d, c5$ment14d_n, useNA='a')

# Sex
c5$sex_n <- NA
c5$sex_n[c5$sex == 1] <- 0
c5$sex_n[c5$sex == 2] <- 1
table(c5$sex, c5$sex_n, useNA='a')

# Age (younger=1)
c5$ageg_n <- NA
c5$ageg_n[c5$age.g %in% c(1, 2, 3)] <- 1
c5$ageg_n[c5$age.g %in% c(4, 5, 6)] <- 0
table(c5$age.g, c5$ageg_n, useNA='a')

# Race (nonwhite = 1)
c5$race_n <- NA
c5$race_n[c5$race == 1] <- 0
c5$race_n[c5$race %in% c(2:8)] <- 1
table(c5$race, c5$race_n, useNA='a')

# Education (college = 1)
c5$educag_n <- NA
c5$educag_n[c5$educag %in% c(1:3)] <- 0
c5$educag_n[c5$educag == 4] <- 1
table(c5$educag, c5$educag_n, useNA='a')

# Income (above median = 1)
# Median household income in 2020 = 67,521
#https://www.census.gov/library/publications/2021/demo/p60-273.html
c5$income2_n <- NA
c5$income2_n[c5$income2 %in% c(1:7)] <- 0
c5$income2_n[c5$income2 == 8] <- 1
table(c5$income2, c5$income2_n, useNA='a')

# Employment status (employed/student/homemaker/retired = 1)
c5$employ1_n <- NA
c5$employ1_n[c5$employ1 %in% c(1,2,5,6,7)] <- 1
c5$employ1_n[c5$employ1 %in% c(3,4,8)] <- 0
table(c5$employ1, c5$employ1_n, useNA='a')


# Delete original variables
c5 <- c5[! names(c5) %in% c("ment14d", "sex", "age.g", "race", "educag", "income2")]

# Or delete all variables except recoded and survey variables
c5 <- c5[! names(c5) %in% c("X", "state", "idate", "dispcode", "ageg5yr", "age65yr", "age.g",
                            "sex", "race", "physhlth", "phys14d", "menthlth", "ment14d", "educag",
                            "incomg", "income2", "employ1", "hcvu651", "hlthcvr1", "llcpwt")]



# Get rid of any row with NA; remaining = 1742245
c5b <- c5[complete.cases(c5) == TRUE, ]

```
 
Demographics for report
```{r}

# Male          Female        Refused_Missing 
# 1067381.67    1125221.98    1377.35 
svytable(~sex_rc, bdesign, Ntotal=2193981)

#   18_24    25_34    35_44    45_54    55_64 65_older sums to 2193981
# 271480.8 381279.1 357982.8 360036.7 364013.3 459188.3
svytable(~ageg_rc, bdesign, Ntotal=2193981)

#white           black          native           asian         pacific           other 
#1340101.633      254485.904       21263.521      116110.722        4406.838       10743.174 
#multi        hispanic Refused_Missing 
#29256.246      373307.292       44305.671 
svytable(~race_rc, bdesign, Ntotal=2193981)

```

Goodness of fit, year by year comparison
```{r}

# 2016 baseline, test 2017
# X-squared = 361.14, df = 2, p-value < 2.2e-16
x <- c(285555.329,	101912.446,	54948.814)
chisq.test(x, p = c(0.657767, 0.225535, 0.116698))

# 2017 baseline, 2018
# X-squared = 55.625, df = 2, p-value = 8.339e-13
x <- c(278004.589,	100959.934,	55174.076)
chisq.test(x, p = c(0.645444,	0.230354,	0.124202))

# 2018 baseline, 2019
# X-squared = 847.68, df = 2, p-value < 2.2e-16
x <- c(249607.901,	99270.991,	54751.189)
chisq.test(x, p = c(0.640359,	0.232552,	0.127089))

# 2019 baseline, 2020
# X-squared = 55.728, df = 2, p-value = 7.922e-13
x <- c(249958.794,	96711.205,	53982.465)
chisq.test(x, p = c(0.618408,	0.245945,	0.135647))

```

Plot proportions for each "mental health days" category from 2016 to 2020
```{r}

# With weighting
svytable(~year + ment14d_rc, bdesign, Ntotal=2193981)

# Split by sex
# something weird with Female 0_days 2020
svytable(~year + ment14d_rc + sex_rc, bdesign, Ntotal=2193981)
# Counts of males/females by year; calculated and filled in that one cell
svytable(~year + sex_rc, bdesign, Ntotal=2193981)

library(ggplot2)

### Proportion by year
mprop <- read.csv('/Users/huiwen/Documents/Work/DS4A/project/data_BFRSS/ment14d_proportion_year.csv', 
                  header=TRUE) 

# Make text labels
label_0 <- data.frame(label = "0 days", x = c(2019), y = c(0.65))
label_113 <- data.frame(label = "1-13 days", x = c(2019), y = c(0.28))
label_14 <- data.frame(label = "14+ days", x = c(2019), y = c(0.175))
label_rm <- data.frame(label = "Missing", x = c(2019), y = c(0.05))

# Export 6 x 8
ggplot(mprop, aes(x = Year, y = Proportion)) + 
  geom_point(size = 3, aes(colour = ment14d, shape = ment14d)) + 
  geom_line(size = 1, aes(colour = ment14d)) + 
    scale_colour_manual(values = c("black", "darkorchid4", "firebrick", "grey")) +
    scale_shape_manual(values = c(19, 15, 17, 4)) +
  scale_x_continuous(name = "Year", limits = c(2016,2020)) + 
  scale_y_continuous(name = "Proportion of respondents", 
                     limits = c(0, 0.8), expand = c(0, 0), breaks = seq(0, 0.8, 0.1)) + 
  ggtitle('Number of poor mental health days in last 30') + 
  theme_bw() +
  theme(legend.position = "none") + 
  theme(plot.margin = unit(c(0.25, 0.5, 0.25, 0.25), "cm")) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.y = element_text(vjust = +1.5), axis.title.x = element_text(vjust = -0.25)) + 
  theme(axis.title = element_text(size = 20), 
    axis.text = element_text(colour = "black", size = 16), 
    text = element_text(size = 20)) + 
  geom_text(label_0, mapping=aes(x = x, y = y, label = label), colour="black", size=6) + 
  geom_text(label_113, mapping=aes(x = x, y = y, label = label), colour="darkorchid4", size=6) +
  geom_text(label_14, mapping=aes(x = x, y = y, label = label), colour="firebrick", size=6) + 
  geom_text(label_rm, mapping=aes(x = x, y = y, label = label), colour="grey", size=4)

### Proportion, by year & sex
msex <- read.csv('/Users/huiwen/Documents/Work/DS4A/project/data_BFRSS/ment14d_proportion_sex.csv', 
                 header=TRUE)
# drop Refused/Missing from sex
msex2 <- msex[msex$Sex != "Refused_Missing", ]

# Make labels for panels
label_0 <- data.frame(label = "0 days", Sex = c("Female", "Male"), 
                      x = c(2019, 2019), y = c(0.6, 0.7))
label_113 <- data.frame(label = "1-13 days", Sex = c("Female", "Male"), 
                        x = c(2019, 2019), y = c(0.31, 0.25))
label_14 <- data.frame(label = "14+ days", Sex = c("Female", "Male"), 
                       x = c(2019, 2019), y = c(0.19, 0.15))
label_rm <- data.frame(label = "Missing", Sex = c("Female", "Male"),
                       x = c(2019, 2019), y = c(0.05, 0.05))

# Export 6 x 9
ggplot(msex2, aes(x = Year, y = Proportion)) + 
  geom_point(size = 3, aes(colour = ment14d, shape = ment14d)) + 
  geom_line(size = 1, aes(colour = ment14d)) + 
    scale_colour_manual(values = c("black", "darkorchid4", "firebrick", "grey")) +
    scale_shape_manual(values = c(19, 15, 17, 4)) +
  facet_grid(~ Sex) + 
  scale_x_continuous(name = "Year", limits = c(2016,2020)) + 
  scale_y_continuous(name = "Proportion of respondents", 
                     limits = c(0, 0.8), expand = c(0, 0), breaks = seq(0, 0.8, 0.1)) + 
  ggtitle('Number of poor mental health days in last 30') + 
  theme_bw() +
  theme(legend.position = "none") + 
  theme(panel.spacing = unit(0.5, "cm")) + 
  theme(strip.background = element_rect(color = "black", fill="white")) + 
  theme(plot.margin = unit(c(0.25, 0.5, 0.25, 0.25), "cm")) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.title.y = element_text(vjust = +1.5), axis.title.x = element_text(vjust = -0.25)) + 
  theme(axis.title = element_text(size = 20), 
    axis.text = element_text(colour = "black", size = 16), 
    text = element_text(size = 20)) + 
  geom_text(label_0, mapping=aes(x = x, y = y, label = label), colour="black", size=6) + 
  geom_text(label_113, mapping=aes(x = x, y = y, label = label), colour="darkorchid4", size=6) +
  geom_text(label_14, mapping=aes(x = x, y = y, label = label), colour="firebrick", size=6) + 
  geom_text(label_rm, mapping=aes(x = x, y = y, label = label), colour="grey", size=4)


```

Test LR smaller sample
```{r}

library(dplyr)

ctemp <- slice_sample(c5, prop=0.01, replace=F)

ct <- ctemp[complete.cases(ctemp) == TRUE, ]

library(survey)

#Error in onestrat(x[index, , drop = FALSE], clusters[index], nPSU[index][1],  : 
  #Stratum (11012) has only one PSU at stage 1
options(survey.lonely.psu = "adjust")

bdesign <- svydesign(id = ~psu, strata = ~ststr, nest = TRUE, weights = ~finalwt, data = ct)

m1 <- svyglm(ment14d_n ~ ageg_n + sex_n, 
             data=ct, design=bdesign, family=quasibinomial())

m2 <- svyglm(ment14d_n ~ ageg_n + sex_n + race_n + educag_n + income2_n, 
             data=ct, design=bdesign, family=quasibinomial())

```

Logistic regression: 0 vs. some days ~ X
```{r}

# stopped this before finishing
# the dreaded error: Error in base::try(strata_psu, silent = TRUE) : object 'strata_psu' not found
# another error: subscript out of bounds

library(survey)

# strata with single PSU OK
options(survey.lonely.psu = "adjust")

bdesign_c5b <- svydesign(id = ~psu, strata = ~ststr, nest = TRUE, weights = ~finalwt, data = c5b)

# 2265.214 seconds!!!
m3 <- svyglm(ment14d_n ~ ageg_n + sex_n + race_n + educag_n + income2_n + employ1_n, 
             data=c5b, design=bdesign_c5b, family=quasibinomial())
summary(m3)
exp(cbind(OR = coef(m3), confint(m3)))

# Proportions of each characteristic
svytable(~ageg_n, bdesign_c5b, Ntotal=1.0)
svytable(~sex_n, bdesign_c5b, Ntotal=1.0)
svytable(~race_n, bdesign_c5b, Ntotal=1.0)
svytable(~educag_n, bdesign_c5b, Ntotal=1.0)
svytable(~income2_n, bdesign_c5b, Ntotal=1.0)
svytable(~employ1_n, bdesign_c5b, Ntotal=1.0)

```

Some exploration
```{r}

length(unique(c5$state)) #54 states

length(unique(c5$ststr)) #1841 strata; combination of geographic regions and telephone/cellphone "banks"?

# Smaller sample for testing
temp <- slice_sample(c5, prop=0.001, replace=F)

# Do some strata only contain 1 PSU? Yes! 
# > summary(strata_psu[,2])
#   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#      1     149     598    1192    1506   28321 
strata_psu = data.frame(strata = integer(), number_psus = integer())
for (i in 1:length(unique(c5$ststr))) { 
  strata_psu[i,1] <- unique(c5$ststr)[i]
  strata_psu[i,2] <- length(unique(c5[c5$ststr == unique(c5$ststr)[i], ]$psu))
}

length(unique(c5$psu)) #128035 PSUs
# the top aggregating variable; where samples must be taken from each to avoid bias
# in BRFSS, varying number of PSUs within each stratum
# one PSU can be found across multiple states but at most once per state, and in only one year
# Official doc: PSU = Annual Sequence Number = Value should be unique for a state for a year.

table(c5$dispcode, useNA='a')/nrow(c5) #0.1572484 complete, 0.8427516 partial

# Beware this is still unweighted
addmargins(prop.table(table(c5$phys14d, c5$year_f), 2), 1)

```
